# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FwB3MCocf9zGFgt6pTUxny5FagCwVe99
"""

import matplotlib.pyplot as plt



#dataset

x=[1,2,3,4,5,6]
y=[2,3,4,5,7,11]

#create a plot for our data
plt.plot(x,y)

#customization for the plot
#add a title first
plt.title('line plot')

#add the labels
plt.xlabel('x-axis')
plt.ylabel('y-axis')

#output the plot
plt.show()

#markers in matplotlib

