# -*- coding: utf-8 -*-
"""array_join.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPnMi_Cw_Fwm0eLbIKiWGn0ACElwhU8t
"""

import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])

concat_array=np.concatenate((array1,array2))
print("concat_array :", concat_array)

array_2d=np.array([1,2,3],[4,5,6])
array_2d2=np.array([7,8,9],[10,11,12],[13,14.15])

#vertically and horizontally
#vstack - for vertical vertical joining
#hstack - for horizontal

#vertically
vstack_array=np.vstack((array2d,array_2d2))
print("vertical staked array is:",vstack_array)

#horizontally
hstack_array=np.hstack((array_2d,array_2d2))
print("vertical staked array is:",hstack_array)

