# -*- coding: utf-8 -*-
"""check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGQIprE5KgcGZJlhTiUUDg1IUbZzuB32
"""

import numpy as np

array=np.array(10,20,12,15,14,17)

#np.where(array==20)
#where(): use to check the perticular condition for filter and condition
#element gretaer than 15 from the above array

elements=np.where(array>15)
print(elements)