# -*- coding: utf-8 -*-
"""numpy3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYUKmI72iJOnCvcudmitp7OQJEw020zB
"""

import numpy as np
# create an original array
original_array=np.array([1,2,3,4,5,6])
print("original_array:",original_array)

#create view for the array
view_array= original_array.view()
print("view of the original array is",view_array)

view_array[2]=30
print("modified view of view_array is:",view_array)

print("original array after modifying view:",original_array)

3#create a copy of original array
copy_array=original_array.copy()
print("copy array:",copy_array)

#modify element in copy array
copy_array[0]=10
print("copy array:",copy_array)

print("original array after modifying copy:",original_array)