# -*- coding: utf-8 -*-
"""leaveout.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pncKPxP7iz_Na0I11BHTfWTHW6pcRkpw
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import LeaveOneOut
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# Load our data
df = pd.read_csv('housing.csv')

# Split the dataset into features and target
x = df[['size', 'bedrooms']].values
y = df['price'].values

# Define the model
model = LinearRegression()

# Define Leave-One-Out cross-validation
loo = LeaveOneOut()
mae_scores = []

for train_index, test_index in loo.split(x):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Train the model
    model.fit(x_train, y_train)

    # Predict the test set
    y_pred = model.predict(x_test)
    mae = mean_absolute_error(y_test, y_pred)
    mae_scores.append(mae)

average_mae = np.mean(mae_scores)
print(f"Average Mean Absolute Error: {average_mae}")